AWSTemplateFormatVersion: 2010-09-09
Description: >-
  nouns-dao-prop-to-snapshot-bot

Transform:
- AWS::Serverless-2016-10-31

Resources:  
  ScheduledEventLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that creates snapshot votes based on NounsDAO props 
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Handler: src/handlers/scheduled-event-logger.scheduledEventLoggerHandler
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
      MemorySize: 128
      Timeout: 100
